 *** caught segfault ***
address (nil), cause 'unknown'
An irrecoverable exception occurred. R is aborting now ...
/home/runner/work/_temp/54d5d467-2f03-41db-8369-d3fbc25da9e8.sh: line 1:  9497 Segmentation fault      (core dumped) Rscript testthat.R
##[error]Process completed with exit code 139.
